PROFILE = {
    "hero_title": "Mình, hôm nay",
    "hero_heading": "Mình,",
    "hero_accent": "hôm nay.",
    "hero_description": "Mình thích tìm hiểu công nghệ, khám phá những nơi mới và chơi cùng những người bạn bốn chân. Đây là một vài lát cắt về mình, từ những kỷ niệm cũ đến cuộc sống hôm nay.",
    "hero_photo": "img/dulich3.jpg",
    "hero_alt": "Một khoảnh khắc nhìn mình qua gương trong chuyến đi",
    "intro_title": "Vài điều",
    "intro_accent": "về mình.",
    "intro": "Mình học An toàn thông tin tại Học viện Kỹ thuật Mật mã. Với mình, công nghệ không chỉ nằm trong sách vở, mà còn ở việc thử một ý tưởng, tìm hiểu cách nó hoạt động và từng bước biến điều mình nghĩ thành điều mình làm được.",
    "intro_more": "Ngoài những giờ học và làm đồ án, mình thích đi đây đó, chụp lại những khung cảnh đẹp và chơi cùng động vật. Những bức ảnh ở đây giữ lại cả hai phần ấy: một mình nghiêm túc với điều đã chọn, và một mình giản dị trong những ngày bình thường.",
    "facts": [
        {
            "label": "Dấu mốc",
            "icon": "route",
            "from_label": "Ngày ấy",
            "to_label": "Hôm nay",
        },
        {"label": "Nơi học", "icon": "school", "value": "Học viện Kỹ thuật Mật mã"},
        {"label": "Chuyên ngành", "icon": "shield", "value": "An toàn thông tin"},
    ],
    "journey_title": "Những ngày",
    "journey_accent": "đã qua.",
    "timeline": [
        {
            "number": "01",
            "title": "Sân trường quen.",
            "text": "Mái trường cũ gắn với những ngày còn nhiều điều chưa biết về mình và tương lai. Nhìn lại sân trường, mình nhớ một khoảng thời gian được học, được thử và bắt đầu nhận ra những điều khiến bản thân tò mò. Đó cũng là một phần của mình hôm nay.",
            "image": "img/AnhTruongC3.jpg",
            "alt": "Khuôn viên trường cấp 3 dưới bầu trời xanh",
            "caption": "Trường cũ",
            "icon": "school",
        },
        {
            "number": "02",
            "title": "Thử sức với STEM.",
            "text": "Cuộc thi STEM là một dịp để mình đưa ý tưởng ra khỏi trang giấy và cùng mọi người thử sức. Tấm ảnh trên sân khấu giữ lại một trải nghiệm khác với giờ học thường ngày: cùng làm một việc, chia sẻ điều đã chuẩn bị và học thêm từ việc dám thử.",
            "image": "img/ThiSTEM.jpg",
            "alt": "Khoảnh khắc trên sân khấu cuộc thi STEM",
            "caption": "Cuộc thi STEM",
            "icon": "atom",
        },
        {
            "number": "03",
            "title": "Chọn một hướng.",
            "text": "Học viện Kỹ thuật Mật mã là nơi mình theo học An toàn thông tin. Lựa chọn ấy đưa sự tò mò về công nghệ vào một hướng rõ ràng hơn. Với mình, quãng thời gian này gắn với việc học cách tự tìm hiểu, kiên trì trước những vấn đề khó và có trách nhiệm với công việc của mình.",
            "image": "img/HVKTMM.jpg",
            "alt": "Cổng Học viện Kỹ thuật Mật mã",
            "caption": "Học viện Kỹ thuật Mật mã",
            "icon": "shield",
        },
        {
            "number": "04",
            "title": "Bảo vệ đồ án.",
            "text": "Buổi bảo vệ đồ án là lúc mình trình bày công việc đã thực hiện và trao đổi với hội đồng về những lựa chọn trong đó. Bức ảnh giữ lại một dấu mốc của quãng thời gian học tập, đồng thời nhắc mình về việc làm đến cùng và hiểu rõ điều mình đã làm.",
            "image": "img/baovedoantotnghiep.png",
            "alt": "Hội đồng bảo vệ đồ án tốt nghiệp ngành An toàn thông tin",
            "caption": "Bảo vệ đồ án tốt nghiệp",
            "icon": "presentation",
        },
    ],
    "travel_title": "Những ngày",
    "travel_accent": "đi xa.",
    "travels": [
        {
            "image": "img/dulich1.jpg",
            "alt": "Lối đi giữa vườn hoa cẩm tú cầu",
            "title": "Giữa màu xanh.",
            "description": "Một lối đi giữa những khóm cẩm tú cầu. Mình thích lưu lại những khung cảnh như thế này, để sau chuyến đi vẫn còn một góc xanh mà nhìn lại.",
        },
        {
            "image": "img/dulich2.jpg",
            "alt": "Con đường gỗ giữa một vườn hoa trắng",
            "title": "Một ngày đầy hoa.",
            "description": "Con đường gỗ, những bông hoa trắng và một khoảng trời yên tĩnh. Đôi khi một chuyến đi đáng nhớ chỉ cần những điều đơn giản như vậy.",
        },
        {
            "image": "img/dulich4.jpg",
            "alt": "Một góc vườn có cây, hoa và bảng gỗ",
            "title": "Góc vườn nhỏ.",
            "description": "Giữa cây, hoa và những chi tiết nhỏ trong vườn, mình có thêm một tấm ảnh để mang về. Một khoảnh khắc bình thường, nhưng là một phần của chuyến đi.",
        },
    ],
    "animal": {
        "image": "img/yeudongvat.png",
        "alt": "Một khoảnh khắc chơi cùng những chú chó",
        "title": "Những người bạn",
        "accent": "bốn chân.",
        "text": "Mình thích dành thời gian chơi cùng động vật, nhất là những chú chó. Không cần một hoạt động cầu kỳ, chỉ ngồi cạnh và chơi cùng các bạn nhỏ cũng là một khoảng nghỉ dễ chịu. Tấm ảnh này giữ lại một phần rất đời thường của mình, bên ngoài những bài học và đồ án.",
    },
}
