PROFILE = {
    "hero_title": "Mình, hôm nay",
    "hero_heading": "Mình,",
    "hero_accent": "hôm nay.",
    "hero_description": "Thích công nghệ, đi đây đó và những người bạn bốn chân.",
    "hero_photo": "img/dulich3.jpg",
    "hero_alt": "Một khoảnh khắc nhìn mình qua gương trong chuyến đi",
    "intro_title": "Vài điều",
    "intro_accent": "về mình.",
    "intro": "Mình đến với công nghệ từ sự tò mò. Qua từng trải nghiệm, mình học cách tự chủ, kiên trì và làm đến cùng.",
    "facts": [
        {"label": "Dấu mốc", "icon": "route", "from_label": "Ngày ấy", "to_label": "Hôm nay"},
        {"label": "Nơi học", "icon": "school", "value": "Học viện Kỹ thuật Mật mã"},
        {"label": "Chuyên ngành", "icon": "shield", "value": "An toàn thông tin"},
    ],
    "journey_title": "Những ngày",
    "journey_accent": "đã qua.",
    "timeline": [
        {
            "number": "01",
            "title": "Sân trường quen.",
            "text": "Mái trường cấp 3, nơi mình bắt đầu nghĩ về tương lai và thấy thích công nghệ.",
            "image": "img/AnhTruongC3.jpg",
            "alt": "Khuôn viên trường cấp 3 dưới bầu trời xanh",
            "caption": "Trường cũ",
            "icon": "school",
        },
        {
            "number": "02",
            "title": "Thử sức với STEM.",
            "text": "Cùng mọi người thử nghiệm ý tưởng và bước lên sân khấu. Một lần học được nhiều điều từ việc dám thử.",
            "image": "img/ThiSTEM.jpg",
            "alt": "Khoảnh khắc trên sân khấu cuộc thi STEM",
            "caption": "Cuộc thi STEM",
            "icon": "atom",
        },
        {
            "number": "03",
            "title": "Chọn một hướng.",
            "text": "Ở Học viện Kỹ thuật Mật mã, mình học An toàn thông tin và nghiêm túc hơn với lựa chọn của mình.",
            "image": "img/HVKTMM.jpg",
            "alt": "Cổng Học viện Kỹ thuật Mật mã",
            "caption": "Học viện Kỹ thuật Mật mã",
            "icon": "shield",
        },
        {
            "number": "04",
            "title": "Bảo vệ đồ án.",
            "text": "Tự trình bày và bảo vệ những gì đã làm. Một dấu mốc để nhìn lại quãng đường mình đã đi.",
            "image": "img/baovedoantotnghiep.png",
            "alt": "Hội đồng bảo vệ đồ án tốt nghiệp ngành An toàn thông tin",
            "caption": "Bảo vệ đồ án tốt nghiệp",
            "icon": "presentation",
        },
    ],
    "travel_title": "Những ngày",
    "travel_accent": "đi xa.",
    "travels": [
        {"image": "img/dulich1.jpg", "alt": "Lối đi giữa vườn hoa cẩm tú cầu", "title": "Giữa màu xanh.", "class_name": "travel-card--wide"},
        {"image": "img/dulich2.jpg", "alt": "Con đường gỗ giữa một vườn hoa trắng", "title": "Một ngày đầy hoa.", "class_name": ""},
        {"image": "img/dulich4.jpg", "alt": "Một góc vườn có cây, hoa và bảng gỗ", "title": "Góc vườn nhỏ.", "class_name": ""},
    ],
    "animal": {
        "image": "img/yeudongvat.png",
        "alt": "Một khoảnh khắc chơi cùng những chú chó",
        "title": "Những người bạn",
        "accent": "bốn chân.",
        "text": "Sau những giờ học và làm việc, mình thích ngồi chơi cùng các bạn nhỏ này.",
    },
}
